"""Task spec defaults for cube_semicircle.

Task: Grasp blue cube, lift 20 cm, carry along a horizontal 180-deg semicircle arc
      (radius 15 cm, sweeping in +X direction), then place down 30 cm to the right.

Trajectory generated by scripts/keypoint_pipeline_par/generate_cube_semicircle_traj.py
"""

from pathlib import Path

_REPO = Path(__file__).parent.parent
_ROBOT_USD = "/mnt/storage/DDDC/Dynamic-Dexterous-Digital-Cousin-Benchmark/realkinova_xhand/realkinova_xhand_right.usd"

DEFAULTS = {
    "robot_usd":            _ROBOT_USD,
    "saved_poses":           str(_REPO / "tasks/saved_poses_20260414_002010.py"),
    "object_usd":            str(_REPO / "assets/objects/blue_cube/cube.usd"),
    "trajectory_json":       "",   # TODO: generate or record cube semicircle trajectory
    "object_scale":          1.0,
    "object_mass":           0.2,
    "success_tolerance":     0.05,
    # Identity orientation: cube sits flat on the table, no rotation baked in.
    "object_orientation":    (1.0, 0.0, 0.0, 0.0),
    # No settle offset: the cube's saved-pose z already rests on the table.
    "object_z_settle_offset": 0.0,
    "task_description": (
        "Object: blue cube, ~0.05 m per side. "
        "Goal: grasp the cube and transport it along a 3-phase trajectory: "
        "(1) lift 20 cm straight up, "
        "(2) carry along a horizontal semicircle arc (radius 15 cm, 180 deg sweep in +X), "
        "(3) lower back to table height 30 cm to the right of initial position. "
        "All 4 bbox-corner keypoints must end within SUCCESS_TOL of GOAL_KEYPOINTS."
    ),
}
